/**
 * The rest of the original's jobs, brought across.
 *
 * The original shipped seventy hand-written ops; the Remake started with fourteen kinds and built
 * every actual job from the world. This file is the other fifty-odd, as data, in the Remake's
 * shape: a target *kind* (a jeweller, one of your own places, somebody whose business you have
 * been inside, a derelict block, a file…), the skills it leans on, what it pays and in what, what
 * it needs before it is on the table, and one named consequence that `remake/sim/catalogue.ts`
 * applies. The job itself — its target, its difficulty, its take — is still read off the city.
 *
 * Numbers come from the original's `OP_DEFS` (content/rackets.ts) so the two games' jobs sit at the
 * same scale: its difficulty, its payout range, its heat, its crew. Where the original named a
 * landmark the Remake does not generate (an observatory, a port), the job points at the nearest
 * thing a Remake city does have, and the comment says which.
 */
import type { BusinessType, JobKind, RacketKind, Skill } from '@r/sim/types';

/** What a catalogue job is pointed at. */
export type JobTarget =
  | 'business'      // somebody else's place, of the listed types
  | 'own'           // a place you own
  | 'rival_racket'  // a place an outfit you are fighting runs something out of
  | 'own_racket'    // a place you run something out of, that an outfit has marked
  | 'npc'           // a civilian with money
  | 'anyone'        // a civilian, rich or not
  | 'official'      // somebody in the building
  | 'inside'        // somebody whose business you have already been inside (see `rat`)
  | 'jailed'        // one of your own, in a cell
  | 'lieutenant'    // a lieutenant of an outfit at war with you
  | 'faction'       // an outfit you are fighting, on its own ground
  | 'block'         // a street (the richer the better)
  | 'derelict'      // a poor block nobody holds
  | 'corner'        // a block with a street crew on it
  | 'district'      // a whole district, worked a night at a time
  | 'landmark'      // a block whose landmark matches
  | 'waterfront'    // a block on the water
  | 'case'          // one open file on you or yours
  | 'none';         // set up from wherever you are standing

/** The one thing a job does beyond its take. Applied in `remake/sim/catalogue.ts`. */
export type CatalogueEffect =
  | 'none' | 'till' | 'owner_fear' | 'insurance' | 'bust_out' | 'soldiers' | 'dig_in' | 'war_kill'
  | 'inside' | 'wreck' | 'corner' | 'recipe' | 'scout' | 'claim' | 'free' | 'cool' | 'file'
  | 'booze' | 'green' | 'charity' | 'dump' | 'friend' | 'ward' | 'wash' | 'supply' | 'bid';

export type PayKind = 'dirty' | 'clean' | 'goods' | 'none';

export interface CatalogueDef {
  label: string;
  verb: string;
  blurb: string;
  target: JobTarget;
  /** For business targets: which kinds of place. Empty means any street business. */
  types?: BusinessType[];
  /** For landmark targets. */
  landmark?: RegExp;
  leans: Skill[];
  /** Hands besides you, the original's min and max. `alone` jobs take nobody. */
  hands: [number, number];
  tier: 1 | 2 | 3 | 4;
  difficulty: number;
  pay: PayKind;
  range: [number, number];
  heat: number;
  crime: 'violence' | 'robbery' | 'murder' | 'fraud' | 'arson' | 'kidnap';
  respect: number;
  fear: number;
  /** Paid when you take it on, win or lose. */
  cost?: number;
  needs?: {
    weapon?: boolean; crew?: number; safehouse?: number; rackets?: RacketKind[];
    /** At least one job of one of these kinds already pulled off. */
    after?: JobKind[];
    notoriety?: number;
  };
  alone?: boolean;
  effect: CatalogueEffect;
  title: string;
  pitch: string;
}

const STREET_RACKETS: RacketKind[] = ['numbers', 'bookmaking', 'gambling_den', 'loansharking', 'fencing', 'dealing', 'chop_shop', 'smuggling', 'laundering', 'no_show_jobs'];

/** Written out, not derived: `CatalogueDef.needs.after` names job kinds, so deriving this from the object is circular. */
export type CatalogueKind =
  | 'heist_jeweller' | 'heist_armored' | 'heist_warehouse' | 'heist_payroll' | 'heist_containers' | 'heist_gallery'
  | 'heist_countroom' | 'count_night' | 'ghost_job' | 'intimidate' | 'armed_robbery' | 'armed_intimidation'
  | 'mugging' | 'porch_piracy' | 'bike_ring' | 'vape_bootleg' | 'copper_strip' | 'squatter_scheme'
  | 'claim_abandoned' | 'takeover' | 'scout_block' | 'ambush_soldiers' | 'defend_racket' | 'war_strike'
  | 'digital_strike' | 'rat' | 'wire_fraud' | 'sim_swap' | 'corporate_extortion' | 'no_loose_ends'
  | 'stream_piracy' | 'betting_app' | 'synth_identity' | 'crypto_wash' | 'insurance_fraud' | 'check_kiting'
  | 'shell_company' | 'charity_front' | 'bust_out' | 'staged_accident' | 'counterfeit_run' | 'straw_purchase'
  | 'resort_fraud' | 'boiler_room' | 'match_fixing' | 'illegal_dumping' | 'dockside_pickup' | 'convoy_run'
  | 'steal_formula' | 'left_luggage' | 'buy_down' | 'spring_crew' | 'prison_supply' | 'buy_case'
  | 'bid_rigging' | 'campaign_wash' | 'vote_buying';

export const CATALOGUE: Record<CatalogueKind, CatalogueDef> = {
  // ------------------------------------------------------------------------------ the heists
  heist_jeweller: { label: 'Jewel heist', verb: 'Take the cases at', blurb: 'Smash and grab, or cut the glass. The loot needs a fence.', target: 'business', types: ['jeweller', 'pawn', 'boutique', 'gallery'], leans: ['brains', 'tech', 'wheels'], hands: [2, 4], tier: 3, difficulty: 60, pay: 'goods', range: [12000, 40000], heat: 20, crime: 'robbery', respect: 10, fear: 2, needs: { safehouse: 2 }, effect: 'till', title: 'The cases at {T}', pitch: '{S} says the display cases at {T} are on a timer, and the timer is on the same circuit as the lights.' },
  heist_armored: { label: 'Armoured car', verb: 'Hit the truck from', blurb: 'The truck on its route. Loud.', target: 'business', types: ['armored_depot', 'bank', 'casino', 'nightclub'], leans: ['muscle', 'wheels', 'brains'], hands: [3, 5], tier: 3, difficulty: 70, pay: 'dirty', range: [25000, 70000], heat: 30, crime: 'robbery', respect: 12, fear: 8, needs: { safehouse: 2, weapon: true }, effect: 'till', title: 'The truck out of {T}', pitch: 'The armoured truck leaves {T} at the same minute every Thursday and takes the same bridge. {S} has timed it twice.' },
  heist_warehouse: { label: 'Warehouse job', verb: 'Empty', blurb: 'Empty a warehouse overnight. Goods, not cash.', target: 'business', types: ['warehouse', 'construction'], leans: ['wheels', 'muscle', 'tech'], hands: [2, 4], tier: 2, difficulty: 45, pay: 'goods', range: [6000, 18000], heat: 12, crime: 'robbery', respect: 5, fear: 1, needs: { crew: 2, rackets: STREET_RACKETS }, effect: 'none', title: 'Empty {T}', pitch: 'Two trucks, one night, and {T} has a loading bay nobody watches after ten.' },
  heist_payroll: { label: 'Payroll snatch', verb: 'Take the wages at', blurb: 'Somebody carries the week\'s wages across a yard once a week, at the same time, with the same two men.', target: 'business', types: ['construction', 'warehouse', 'cab_company', 'garage', 'scrapyard'], leans: ['muscle', 'wheels'], hands: [1, 3], tier: 2, difficulty: 48, pay: 'dirty', range: [4000, 14000], heat: 16, crime: 'robbery', respect: 5, fear: 6, needs: { weapon: true, crew: 1 }, effect: 'none', title: 'Payday at {T}', pitch: 'Friday at four, the wages for {T} cross the yard in a canvas bag. Two men walk it. Neither of them is paid enough to argue.' },
  heist_containers: { label: 'Container job', verb: 'Lift a box from', blurb: 'One box off a stack of thousands, and a manifest that never mentions it.', target: 'business', types: ['warehouse'], leans: ['wheels', 'brains', 'tech'], hands: [2, 4], tier: 2, difficulty: 55, pay: 'goods', range: [9000, 26000], heat: 14, crime: 'robbery', respect: 6, fear: 0, needs: { crew: 2 }, effect: 'none', title: 'One box at {T}', pitch: 'There is a container at {T} that three different people want to know about. {S} knows which one it is.' },
  heist_gallery: { label: 'The collection', verb: 'Lift the collection at', blurb: 'Things worth far more than anybody will openly pay for them. A fence takes the difference.', target: 'business', types: ['gallery', 'jeweller', 'pawn'], leans: ['tech', 'brains', 'wheels'], hands: [2, 4], tier: 3, difficulty: 68, pay: 'goods', range: [20000, 55000], heat: 22, crime: 'robbery', respect: 12, fear: 0, needs: { safehouse: 2, after: ['heist_jeweller'] }, effect: 'till', title: 'The back room at {T}', pitch: 'What {T} keeps out front is for the tourists. What it keeps in the back has no price on it, and no insurance either.' },
  heist_countroom: { label: 'The count room', verb: 'Hit the count at', blurb: 'The room behind the floor, on the night the week is counted. You need to have walked it first.', target: 'business', types: ['nightclub'], leans: ['brains', 'muscle', 'tech', 'charm'], hands: [3, 5], tier: 4, difficulty: 78, pay: 'dirty', range: [35000, 95000], heat: 32, crime: 'robbery', respect: 16, fear: 8, needs: { crew: 3, safehouse: 2, notoriety: 75 }, effect: 'till', title: 'Count night at {T}', pitch: 'Sunday night {T} counts the week in a room behind the bar. {S} has been inside it, and drew you the door.' },
  count_night: { label: 'Casino count', verb: 'Take the count at', blurb: 'One night a month everything that came through the doors is in one room being counted.', target: 'business', types: ['casino'], leans: ['brains', 'muscle', 'tech', 'charm'], hands: [2, 5], tier: 4, difficulty: 74, pay: 'dirty', range: [45000, 130000], heat: 30, crime: 'robbery', respect: 18, fear: 6, needs: { safehouse: 2, notoriety: 90 }, effect: 'till', title: 'The monthly count at {T}', pitch: 'Once a month {T} counts everything at once, in one room, with the doors locked from the inside. From the inside.' },
  ghost_job: { label: 'Nobody saw anybody', verb: 'Take apart', blurb: 'You, alone, at your own pace. No second person for anybody to describe.', target: 'business', types: [], leans: ['brains', 'tech', 'wheels'], hands: [0, 0], tier: 2, difficulty: 48, pay: 'goods', range: [2500, 8000], heat: 0, crime: 'robbery', respect: 3, fear: 0, needs: { safehouse: 1 }, alone: true, effect: 'till', title: 'Alone at {T}', pitch: 'One person, one night, {T}. No crew means nobody to flip.' },

  // ---------------------------------------------------------------------- street, rough
  intimidate: { label: 'Send a message', verb: 'Send a message to', blurb: 'Bats and broken windows. Fear without a body.', target: 'business', types: [], leans: ['muscle'], hands: [0, 3], tier: 1, difficulty: 25, pay: 'none', range: [0, 0], heat: 6, crime: 'violence', respect: 0, fear: 6, effect: 'owner_fear', title: 'A message for {T}', pitch: '{S} would like {T} to understand something, and would like it understood tonight.' },
  armed_robbery: { label: 'Armed robbery', verb: 'Hold up', blurb: 'Not a demand. An instruction. Everything in the drawer, and the safe.', target: 'business', types: [], leans: ['muscle', 'wheels'], hands: [0, 3], tier: 1, difficulty: 40, pay: 'dirty', range: [1600, 6000], heat: 18, crime: 'robbery', respect: 2, fear: 8, needs: { weapon: true }, effect: 'till', title: 'Guns out at {T}', pitch: '{T} keeps a safe under the counter and the owner has been heard to say so.' },
  armed_intimidation: { label: 'Armed message', verb: 'Show a gun at', blurb: 'They see it. Nobody has to use it. Nobody argues afterwards.', target: 'business', types: [], leans: ['muscle', 'charm'], hands: [0, 3], tier: 1, difficulty: 28, pay: 'none', range: [0, 0], heat: 10, crime: 'violence', respect: 0, fear: 10, needs: { weapon: true }, effect: 'owner_fear', title: 'Let {T} see it', pitch: 'The owner of {T} has stopped listening to words.' },
  mugging: { label: 'Mugging', verb: 'Roll', blurb: 'Follow somebody off a lit street and take what is on them.', target: 'anyone', leans: ['muscle', 'wheels'], hands: [0, 2], tier: 1, difficulty: 28, pay: 'dirty', range: [120, 900], heat: 7, crime: 'violence', respect: 0, fear: 2, effect: 'none', title: 'Follow {T} home', pitch: '{T} walks home the same way every night, past the same dark stretch.' },
  porch_piracy: { label: 'Doorstep runs', verb: 'Work the doorsteps of', blurb: 'Follow the vans round the good streets and take what they leave on the step.', target: 'block', leans: ['wheels', 'brains'], hands: [0, 2], tier: 1, difficulty: 22, pay: 'goods', range: [150, 600], heat: 3, crime: 'robbery', respect: 0, fear: 0, effect: 'none', title: 'Doorsteps on {T}', pitch: 'The delivery vans do {T} between two and four. Nobody is home.' },
  bike_ring: { label: 'Bike ring', verb: 'Work', blurb: 'Two kids, a van and bolt croppers, working a district a night.', target: 'district', leans: ['wheels', 'muscle'], hands: [1, 3], tier: 1, difficulty: 28, pay: 'goods', range: [400, 1400], heat: 5, crime: 'robbery', respect: 1, fear: 0, needs: { crew: 1 }, effect: 'none', title: 'A night in {T} with the croppers', pitch: 'Every rack in {T} has a bike on it worth what a car was ten years ago.' },
  vape_bootleg: { label: 'Bootleg smokes', verb: 'Sell cartons across', blurb: 'Cartons off a lorry that was going somewhere else, sold at half the shop price.', target: 'district', leans: ['charm', 'wheels'], hands: [0, 2], tier: 1, difficulty: 26, pay: 'dirty', range: [500, 1600], heat: 4, crime: 'fraud', respect: 1, fear: 0, effect: 'none', title: 'Cartons across {T}', pitch: 'A lorry-load of smokes needs a hundred counters in {T} by the weekend.' },
  copper_strip: { label: 'Strip it for copper', verb: 'Strip', blurb: 'A building nobody is watching, and everything in the walls worth money by the kilo.', target: 'derelict', leans: ['muscle', 'tech'], hands: [1, 3], tier: 1, difficulty: 30, pay: 'goods', range: [600, 2200], heat: 6, crime: 'robbery', respect: 1, fear: 0, needs: { crew: 1 }, effect: 'none', title: 'The copper on {T}', pitch: 'Half of {T} has been empty for years, and the wiring is still in the walls.' },
  squatter_scheme: { label: 'Rent what is not yours', verb: 'Let rooms on', blurb: 'People in an empty building, paying you every week. The paperwork is somebody else\'s problem.', target: 'derelict', leans: ['charm', 'brains'], hands: [1, 2], tier: 1, difficulty: 34, pay: 'dirty', range: [900, 3000], heat: 5, crime: 'fraud', respect: 1, fear: 1, needs: { crew: 1 }, effect: 'claim', title: 'Tenants on {T}', pitch: 'Nobody owns the empty buildings on {T} that anybody can find. You could.' },
  claim_abandoned: { label: 'Take the lot', verb: 'Move in on', blurb: 'A derelict block: clear whoever is sleeping there, or buy the paperwork.', target: 'derelict', leans: ['muscle', 'brains'], hands: [0, 3], tier: 1, difficulty: 35, pay: 'none', range: [0, 0], heat: 6, crime: 'violence', respect: 3, fear: 2, effect: 'claim', title: 'Put your name on {T}', pitch: 'Nobody collects rent on {T}. Nobody would notice if somebody started.' },
  takeover: { label: 'Take the corner', verb: 'Take the corner at', blurb: 'Roll up on a street crew and take their block. Lighter than a raid.', target: 'corner', leans: ['muscle', 'charm'], hands: [0, 3], tier: 1, difficulty: 35, pay: 'dirty', range: [300, 1200], heat: 8, crime: 'violence', respect: 3, fear: 5, effect: 'corner', title: 'The corner on {T}', pitch: 'The kids on {T} have been skimming your street for weeks. {S} knows when they are all in one place.' },
  scout_block: { label: 'Scout the edges', verb: 'Walk', blurb: 'Walk the dead streets at the edge of a district and find out what is still standing.', target: 'district', leans: ['brains', 'wheels', 'tech'], hands: [0, 2], tier: 1, difficulty: 30, pay: 'none', range: [0, 0], heat: 2, crime: 'violence', respect: 1, fear: 0, effect: 'scout', title: 'Walk the edges of {T}', pitch: 'Nobody has looked properly at the far end of {T} in years. People live there. Some of them need things.' },

  // -------------------------------------------------------------------------------- war
  ambush_soldiers: { label: 'Ambush their soldiers', verb: 'Ambush', blurb: 'Catch a crew of theirs off their own turf and take the fight to them for once.', target: 'faction', leans: ['muscle', 'wheels'], hands: [1, 4], tier: 2, difficulty: 45, pay: 'dirty', range: [800, 3500], heat: 14, crime: 'violence', respect: 5, fear: 8, effect: 'soldiers', title: 'Catch the {T} out', pitch: 'A carload of {T} soldiers drinks at the same bar every Tuesday, a long way from home.' },
  defend_racket: { label: 'Dig in', verb: 'Dig in at', blurb: 'Put people on a place they have marked, and be there when the muscle arrives.', target: 'own_racket', leans: ['muscle', 'brains'], hands: [1, 3], tier: 1, difficulty: 35, pay: 'none', range: [0, 0], heat: 5, crime: 'violence', respect: 4, fear: 3, effect: 'dig_in', title: 'Dig in at {T}', pitch: 'The word is they are coming for {T}. Be there first.' },
  war_strike: { label: 'War strike', verb: 'Take off the board', blurb: 'One of their lieutenants, while the shooting has already started. Read as an act of war.', target: 'lieutenant', leans: ['muscle', 'wheels', 'brains'], hands: [2, 4], tier: 3, difficulty: 55, pay: 'none', range: [0, 0], heat: 20, crime: 'murder', respect: 8, fear: 12, needs: { crew: 2 }, effect: 'war_kill', title: 'Take {T} off the board', pitch: '{T} runs their side of the war from a car that parks in the same place every morning.' },
  digital_strike: { label: 'Pull their wires', verb: 'Pull the wires at', blurb: 'Their tills stop ringing and their book stops balancing. Nobody sees you.', target: 'rival_racket', leans: ['tech', 'brains'], hands: [0, 2], tier: 2, difficulty: 48, pay: 'dirty', range: [200, 1200], heat: 6, crime: 'fraud', respect: 3, fear: 0, effect: 'wreck', title: 'Switch off {T}', pitch: 'The operation they run out of {T} lives on one laptop and a router in the back.' },

  // ------------------------------------------------------------------------- the wire
  rat: { label: 'Get inside their business', verb: 'Get inside', blurb: 'Their post, their calls, their arrangements. Learn what they are hiding.', target: 'npc', leans: ['tech', 'brains'], hands: [0, 2], tier: 1, difficulty: 45, pay: 'none', range: [0, 0], heat: 4, crime: 'fraud', respect: 1, fear: 0, effect: 'inside', title: 'Inside {T}\'s business', pitch: '{T} has money, secrets and a phone that has never had a password.' },
  wire_fraud: { label: 'Wire fraud', verb: 'Move the money of', blurb: 'Their arrangements, in your name, moved somewhere quiet. Only once you have been inside.', target: 'inside', leans: ['tech', 'brains'], hands: [0, 2], tier: 3, difficulty: 56, pay: 'clean', range: [9000, 30000], heat: 16, crime: 'fraud', respect: 4, fear: 0, effect: 'none', title: '{T}\'s accounts', pitch: 'You have been reading {T}\'s post for a while. The bank will take instructions from anybody who writes like them.' },
  sim_swap: { label: 'Take their number', verb: 'Take the number of', blurb: 'Their phone stops working and everything tied to it answers to somebody else for an afternoon.', target: 'inside', leans: ['tech', 'charm'], hands: [0, 2], tier: 1, difficulty: 42, pay: 'dirty', range: [1200, 5000], heat: 6, crime: 'fraud', respect: 1, fear: 0, effect: 'none', title: '{T}\'s phone', pitch: 'A clerk at the phone shop owes you, and {T} has everything on one number.' },
  corporate_extortion: { label: 'Lean on the board', verb: 'Lean on', blurb: 'A company, a quarterly number, and something they would rather nobody read.', target: 'inside', leans: ['brains', 'charm'], hands: [2, 4], tier: 3, difficulty: 60, pay: 'clean', range: [10000, 32000], heat: 13, crime: 'fraud', respect: 6, fear: 4, needs: { crew: 3 }, effect: 'none', title: 'What {T} would rather nobody read', pitch: 'What you found inside {T}\'s business would end a board meeting. They can buy it back.' },
  no_loose_ends: { label: 'No loose ends', verb: 'Quietly take', blurb: 'Weeks of being the only person who knows. Nobody to flip, nothing that comes back.', target: 'inside', leans: ['brains', 'charm', 'tech'], hands: [0, 0], tier: 3, difficulty: 58, pay: 'clean', range: [11000, 32000], heat: 4, crime: 'fraud', respect: 4, fear: 0, alone: true, needs: { after: ['ghost_job'] }, effect: 'none', title: 'Just you and {T}', pitch: 'You know enough about {T} to do this with nobody else in the room.' },
  stream_piracy: { label: 'Pirate feeds', verb: 'Resell the feeds across', blurb: 'Somebody else\'s channels, resold by the month to half a district.', target: 'district', leans: ['tech', 'brains'], hands: [0, 2], tier: 2, difficulty: 40, pay: 'dirty', range: [2000, 7000], heat: 5, crime: 'fraud', respect: 1, fear: 0, needs: { safehouse: 1 }, effect: 'none', title: 'Every screen in {T}', pitch: 'Half of {T} would pay a tenner a month for everything. The other half already does, to somebody.' },
  betting_app: { label: 'Run a book online', verb: 'Put a book on the phones of', blurb: 'The same book, on everybody\'s phone, with no door to raid.', target: 'none', leans: ['tech', 'brains'], hands: [0, 3], tier: 2, difficulty: 50, pay: 'dirty', range: [4000, 13000], heat: 8, crime: 'fraud', respect: 2, fear: 0, needs: { rackets: ['bookmaking', 'gambling_den', 'numbers'] }, effect: 'none', title: 'The book, online', pitch: 'The same punters, the same odds, and nowhere for the police to kick in.' },
  synth_identity: { label: 'Build a person', verb: 'Build', blurb: 'A name that belongs to nobody, with a history, a rating and a signature.', target: 'none', leans: ['tech', 'brains'], hands: [0, 2], tier: 2, difficulty: 52, pay: 'clean', range: [3500, 12000], heat: 7, crime: 'fraud', respect: 1, fear: 0, needs: { after: ['shell_company', 'wire_fraud'] }, effect: 'none', title: 'Somebody who does not exist', pitch: 'A birth certificate, a credit file and a bank that has never met them.' },
  crypto_wash: { label: 'Wash it sideways', verb: 'Wash', blurb: 'Money in one shape, out in another, through enough hands that nobody is sure which were yours.', target: 'none', leans: ['tech', 'brains'], hands: [0, 3], tier: 4, difficulty: 60, pay: 'none', range: [0, 0], heat: 9, crime: 'fraud', respect: 2, fear: 0, needs: { safehouse: 2, after: ['wire_fraud', 'shell_company'] }, effect: 'wash', title: 'Sideways', pitch: 'Up to twenty-five thousand dirty, through wallets and exchanges, out clean at eighty-five cents.' },

  // --------------------------------------------------------------------------- paper
  insurance_fraud: { label: 'Insurance fraud', verb: 'Torch your own', blurb: 'Torch your own insured place, collect the policy.', target: 'own', leans: ['tech', 'brains'], hands: [1, 2], tier: 1, difficulty: 40, pay: 'clean', range: [0, 0], heat: 10, crime: 'arson', respect: 0, fear: 0, effect: 'insurance', title: 'An accident at {T}', pitch: '{T} is insured for more than it will ever earn. Electrical fires happen.' },
  check_kiting: { label: 'Check kiting', verb: 'Float paper through', blurb: 'Bad paper between banks, through a front you own.', target: 'own', leans: ['brains'], hands: [1, 2], tier: 1, difficulty: 50, pay: 'clean', range: [5000, 15000], heat: 8, crime: 'fraud', respect: 1, fear: 0, effect: 'none', title: 'Paper through {T}', pitch: 'Three banks, two days of float, and {T}\'s account in the middle.' },
  shell_company: { label: 'Shell company', verb: 'Bill', blurb: 'A company on paper, billing a place you own for work nobody did. Slow, dull, and clean.', target: 'own', leans: ['brains', 'charm'], hands: [0, 2], tier: 3, difficulty: 54, pay: 'clean', range: [7000, 20000], heat: 4, crime: 'fraud', respect: 2, fear: 0, needs: { crew: 1 }, effect: 'none', title: 'Invoices to {T}', pitch: 'A consultancy, a letterhead, and {T} paying it every month.' },
  charity_front: { label: 'Charity front', verb: 'Collect for a cause at', blurb: 'A collection nobody can argue with, run out of a place you own. The city likes you more.', target: 'own', leans: ['charm', 'brains'], hands: [0, 2], tier: 2, difficulty: 48, pay: 'clean', range: [4000, 12000], heat: 3, crime: 'fraud', respect: 5, fear: 0, effect: 'charity', title: 'A collection at {T}', pitch: 'Orphans, widows and a jar on the counter at {T}. Most of it even goes somewhere.' },
  bust_out: { label: 'Bust-out', verb: 'Bust out', blurb: 'Order everything its name will carry, sell it all, and walk away from the bill.', target: 'own', leans: ['brains', 'charm'], hands: [2, 4], tier: 3, difficulty: 56, pay: 'dirty', range: [12000, 38000], heat: 16, crime: 'fraud', respect: 3, fear: 0, needs: { after: ['shell_company'] }, effect: 'bust_out', title: 'Bust out {T}', pitch: '{T} has good credit with every supplier in the city. For about three more weeks.' },
  staged_accident: { label: 'Staged accident', verb: 'Slip over in', blurb: 'Somebody slips in a place that is insured, and a claim follows.', target: 'business', types: ['restaurant', 'diner', 'bar', 'motel', 'gym', 'boutique', 'corner_store', 'pharmacy'], leans: ['charm', 'brains'], hands: [1, 2], tier: 2, difficulty: 45, pay: 'clean', range: [3000, 9000], heat: 6, crime: 'fraud', respect: 1, fear: 0, needs: { crew: 1 }, effect: 'none', title: 'A nasty fall at {T}', pitch: 'The floor at {T} is always wet by the kitchen door, and their insurer always settles.' },
  counterfeit_run: { label: 'Counterfeit run', verb: 'Print', blurb: 'A print run of something that is not what it says it is, moved through a racket of your own.', target: 'none', leans: ['tech', 'brains'], hands: [1, 3], tier: 2, difficulty: 55, pay: 'goods', range: [4000, 12000], heat: 12, crime: 'fraud', respect: 2, fear: 0, cost: 2000, needs: { crew: 1, rackets: ['fencing', 'smuggling', 'laundering', 'no_show_jobs', 'counterfeiting', 'card_skimming'] }, effect: 'none', title: 'A print run', pitch: 'Plates, paper, ink and a warehouse with the windows painted over.' },
  straw_purchase: { label: 'Straw buyers', verb: 'Send straw buyers out for', blurb: 'Other people\'s names on paperwork for cars and goods that were never theirs.', target: 'none', leans: ['charm', 'brains'], hands: [1, 3], tier: 2, difficulty: 44, pay: 'dirty', range: [2500, 8000], heat: 8, crime: 'fraud', respect: 1, fear: 0, needs: { crew: 2 }, effect: 'none', title: 'Straw buyers', pitch: 'Ten people with clean names, ten dealerships, one weekend.' },
  resort_fraud: { label: 'Timeshare sell', verb: 'Sell a week in the sun to', blurb: 'A room, a slideshow and a week in the sun that does not exist.', target: 'none', leans: ['charm', 'brains'], hands: [1, 3], tier: 2, difficulty: 48, pay: 'dirty', range: [4000, 14000], heat: 7, crime: 'fraud', respect: 1, fear: 0, needs: { crew: 2, after: ['con', 'shell_company'] }, effect: 'none', title: 'A week in the sun', pitch: 'A hired function room, free drinks and a brochure. They sign because everybody else is signing.' },
  boiler_room: { label: 'Boiler room', verb: 'Run the phones for', blurb: 'Twenty phones, twenty scripts and a company that is a filing cabinet.', target: 'none', leans: ['charm', 'brains'], hands: [2, 5], tier: 3, difficulty: 58, pay: 'dirty', range: [14000, 45000], heat: 14, crime: 'fraud', respect: 3, fear: 0, needs: { crew: 3, after: ['shell_company', 'con'] }, effect: 'none', title: 'The boiler room', pitch: 'An office above a shop, twenty phones and a stock that will go up any day now.' },
  match_fixing: { label: 'Fix the card', verb: 'Fix a fight with', blurb: 'One professional who needs money more than the result. The book does the rest.', target: 'npc', leans: ['charm', 'muscle'], hands: [1, 2], tier: 2, difficulty: 50, pay: 'dirty', range: [3000, 11000], heat: 9, crime: 'fraud', respect: 2, fear: 2, needs: { rackets: ['bookmaking', 'numbers', 'gambling_den'] }, effect: 'none', title: 'A dive for {T}', pitch: '{T} owes money to the wrong people and has a fight on Saturday.' },
  illegal_dumping: { label: 'Take the contract', verb: 'Dump barrels in', blurb: 'Somebody pays well to have barrels go away. Where they go is a district that will not find out for years.', target: 'district', leans: ['wheels', 'muscle'], hands: [1, 3], tier: 2, difficulty: 42, pay: 'dirty', range: [3000, 10000], heat: 10, crime: 'fraud', respect: 1, fear: 0, needs: { crew: 2, rackets: ['union_dues', 'no_show_jobs', 'smuggling'] }, effect: 'dump', title: 'Barrels into {T}', pitch: 'A chemical works pays by the barrel, and nobody in {T} checks what is under the new car park.' },

  // --------------------------------------------------------------------- moving product
  dockside_pickup: { label: 'Dockside pickup', verb: 'Meet a boat at', blurb: 'Meet a boat that is not on any schedule and be gone before the shift changes.', target: 'waterfront', leans: ['wheels', 'charm'], hands: [1, 3], tier: 2, difficulty: 45, pay: 'none', range: [0, 0], heat: 9, crime: 'robbery', respect: 2, fear: 0, cost: 2200, needs: { crew: 1, after: ['smuggle'] }, effect: 'booze', title: 'A boat at {T}', pitch: 'A boat that is not on any schedule ties up off {T} at three in the morning.' },
  convoy_run: { label: 'Run a convoy', verb: 'Run four vans through', blurb: 'Not one van but four, on one night. The whole quarter\'s product in one move.', target: 'none', leans: ['wheels', 'brains', 'muscle'], hands: [3, 5], tier: 3, difficulty: 66, pay: 'none', range: [0, 0], heat: 20, crime: 'robbery', respect: 6, fear: 2, cost: 6000, needs: { crew: 3, safehouse: 2, after: ['dockside_pickup'] }, effect: 'green', title: 'The convoy', pitch: 'Four vans, four routes, one night. If one is stopped the other three still get home.' },
  steal_formula: { label: 'Steal a formula', verb: 'Lift the recipe from', blurb: 'Break into a rival cook, a pharmacy or a print works and leave with something you can use.', target: 'business', types: ['pharmacy', 'warehouse', 'electronics'], leans: ['tech', 'brains'], hands: [1, 3], tier: 2, difficulty: 50, pay: 'none', range: [0, 0], heat: 10, crime: 'robbery', respect: 3, fear: 0, needs: { crew: 2, rackets: STREET_RACKETS }, effect: 'recipe', title: 'The book at {T}', pitch: 'Whoever cooks for the people behind {T} writes it all down. Your labs would run better on it.' },
  left_luggage: { label: 'Left luggage', verb: 'Work the crowds at', blurb: 'Forty thousand people a day, all carrying something, none of them looking at anybody.', target: 'landmark', landmark: /terminal|tram depot|ferry pier|stadium|market|racetrack|opera|hotel|city hall|cathedral/, leans: ['charm', 'brains', 'wheels'], hands: [0, 2], tier: 2, difficulty: 44, pay: 'dirty', range: [2500, 9000], heat: 7, crime: 'robbery', respect: 2, fear: 0, effect: 'none', title: 'The lockers at {T}', pitch: 'The left-luggage lockers at {T} open with any of three keys. {S} has all three.' },

  // ------------------------------------------------------------------------- the law
  buy_down: { label: 'Buy down the heat', verb: 'Buy the attention of', blurb: 'Pay somebody inside the building for their attention to go elsewhere.', target: 'official', leans: ['charm', 'brains'], hands: [0, 2], tier: 2, difficulty: 45, pay: 'none', range: [0, 0], heat: 3, crime: 'fraud', respect: 1, fear: 0, cost: 3000, needs: { crew: 1 }, effect: 'cool', title: 'A word with {T}', pitch: '{T} has a mortgage, and you have an envelope.' },
  spring_crew: { label: 'Spring somebody', verb: 'Spring', blurb: 'Get one of your own out before their sentence runs.', target: 'jailed', leans: ['brains', 'tech', 'charm'], hands: [0, 3], tier: 2, difficulty: 54, pay: 'none', range: [0, 0], heat: 14, crime: 'fraud', respect: 4, fear: 1, cost: 2500, effect: 'free', title: 'Get {T} out', pitch: 'A transfer that goes wrong, a signature in the right place. {T} walks out on Tuesday.' },
  prison_supply: { label: 'Supply the wing', verb: 'Carry things in to', blurb: 'One of yours is inside, and everything in there costs ten times what it does out here.', target: 'jailed', leans: ['charm', 'muscle'], hands: [1, 3], tier: 3, difficulty: 50, pay: 'dirty', range: [3000, 9000], heat: 9, crime: 'fraud', respect: 2, fear: 1, needs: { after: ['spring_crew'] }, effect: 'supply', title: 'A wing for {T}', pitch: '{T} can move anything once it is inside. Getting it inside is your end.' },
  buy_case: { label: 'Kill a file', verb: 'Lose the file on', blurb: 'Paper misfiled, an exhibit lost, a detective reassigned. This is the file itself.', target: 'case', leans: ['brains', 'charm'], hands: [0, 2], tier: 3, difficulty: 56, pay: 'none', range: [0, 0], heat: 6, crime: 'fraud', respect: 2, fear: 0, cost: 4000, needs: { crew: 1 }, effect: 'file', title: 'Lose the file: {T}', pitch: 'A clerk in records can make a box disappear. It will cost, and it has to be done right the first time.' },
  bid_rigging: { label: 'Rig the bidding', verb: 'Rig a contract through', blurb: 'The contract was always going to somebody. A councillor who takes your calls decides it goes to you.', target: 'official', leans: ['brains', 'charm'], hands: [1, 3], tier: 3, difficulty: 55, pay: 'clean', range: [15000, 50000], heat: 12, crime: 'fraud', respect: 4, fear: 0, needs: { crew: 2, notoriety: 60 }, effect: 'bid', title: 'A contract through {T}', pitch: 'The city is tendering for three years of road repairs. {T} scores the bids.' },
  campaign_wash: { label: 'Fund a friend', verb: 'Fund the campaign of', blurb: 'Money into a campaign through a hundred names that are not yours, and a friend in the building afterwards.', target: 'official', leans: ['charm', 'brains'], hands: [1, 3], tier: 3, difficulty: 57, pay: 'none', range: [0, 0], heat: 10, crime: 'fraud', respect: 5, fear: 0, cost: 12000, needs: { rackets: ['laundering'] }, effect: 'friend', title: 'A friend in {T}', pitch: '{T} is up for re-election and short of money. A hundred small donors could fix that.' },
  vote_buying: { label: 'Buy the ward', verb: 'Buy', blurb: 'A ward, paid for door by door, and a result everybody can see and nobody can prove.', target: 'district', leans: ['charm', 'brains'], hands: [2, 5], tier: 4, difficulty: 66, pay: 'none', range: [0, 0], heat: 15, crime: 'fraud', respect: 10, fear: 2, cost: 20000, needs: { crew: 4, after: ['campaign_wash'] }, effect: 'ward', title: 'Every door in {T}', pitch: 'An election in {T}, and every door on every street for sale at forty dollars.' },
};
export const CATALOGUE_KINDS = Object.keys(CATALOGUE) as CatalogueKind[];
export const isCatalogue = (k: string): k is CatalogueKind => k in CATALOGUE;
