/**
 * The handful of places in the city that are only there once.
 *
 * Everything else on the map is generated from a type: there are eleven bars and they differ by
 * name, income and who owns them. A landmark is the opposite — one building, placed once, with a
 * job that exists nowhere else and cannot be practised on something smaller.
 *
 * They are ordinary `Business` records of ordinary types, so every system in the game reads them
 * without a special case: you can case one, buy one (if you can clear the tier-4 standing floor),
 * run its racket, watch a faction take protection on it. The only thing that makes one a landmark
 * is `Business.landmark`, and the only thing that field does is unlock one op.
 */
import type { BusinessType, OpKind, Role, Skills, Trait } from '@sim/types';

export type LandmarkId = 'grand_casino' | 'courthouse' | 'port' | 'central_station' | 'observatory';

export interface LandmarkDef {
  id: LandmarkId;
  name: string;
  /** What kind of building it is, so it generates and behaves like anything else of that type. */
  type: BusinessType;
  /** The district it wants. Falls back to anywhere if the city has none of that kind. */
  district: string;
  blurb: string;
  /** The one job that exists only here. */
  op: OpKind;
  /**
   * The second reason to know the building, and there is exactly one per landmark.
   *
   * A landmark used to be worth precisely one op, and an op you can pull once every few weeks is
   * a thin reason to walk across the city. Each of the five now has a standing draw as well —
   * whichever of the two fits what the place already is. A courthouse basement full of everybody's
   * paper is a *person* you go and see; nine miles of dock fence is a *thing* you can buy there.
   *
   * Never both. A landmark with a person and an item would be a hub, and the map already has
   * those; the point of these is that they are one building with one specific thing in it.
   */
  person?: LandmarkPerson;
  /** An `ITEM_DEFS` id sold here and in no other building in the city. */
  item?: string;
}

/**
 * Somebody who is always at this landmark.
 *
 * Generated by **promotion**, exactly as the building itself is (`sim/generate.ts`): a person the
 * block already had is renamed and given this record, so nothing new is placed and not one number
 * comes off the rng. They arrive `known`, because everybody knows who runs the count room.
 *
 * `skills` is the part that makes them mechanically worth the walk rather than flavour: every one
 * of these is above the floor `sim/specialists.ts` asks for, so each of these three landmarks is
 * where you go to staff the part of a heist it is named for.
 */
export interface LandmarkPerson {
  name: string;
  role: Role;
  trait: Trait;
  nerve: number;
  /** Set on the record, so their sheet says why they matter without anything having to explain it. */
  note: string;
  /** Raised to at least these. Anything not listed is whatever the city already gave them. */
  skills: Partial<Skills>;
}

export const LANDMARKS: LandmarkDef[] = [
  {
    id: 'grand_casino', name: 'The Grand', type: 'casino', district: 'strip',
    blurb: 'Four floors, two thousand people a night, and a count room nobody has ever seen twice.',
    op: 'count_night',
    // The house's own man. He is not hired help and he is not bent — he is simply the one person
    // in the city who has been inside the count room, which is worth more than either.
    person: {
      name: 'Solomon "Sunday" Reyes', role: 'patron', trait: 'quiet', nerve: 78,
      note: 'Counts the drop at The Grand and has done for nineteen years. Has been inside the room.',
      skills: { charm: 8, brains: 7 },
    },
  },
  {
    id: 'courthouse', name: 'County Courthouse', type: 'development_co', district: 'downtown',
    blurb: 'Everything anybody ever did to anybody in this city, in a basement, in boxes.',
    op: 'records_room',
    // A basement full of everybody's paper, and one man who knows where all of it is. He does not
    // steal it for you; he makes you a fresh sheet that looks like it has been down there for years.
    person: {
      name: 'Edna Kowalczyk', role: 'patron', trait: 'greedy', nerve: 52,
      note: 'Files at the County Courthouse. Can make a document that has always been there.',
      skills: { brains: 9, tech: 6 },
    },
  },
  {
    id: 'port', name: 'The Port Authority', type: 'shipping_line', district: 'docks',
    blurb: 'Nine miles of fence and a manifest for every box behind it.',
    op: 'manifest_swap',
    // Nine miles of fence, and the only way through it that is not over it.
    item: 'port_pass',
  },
  {
    id: 'central_station', name: 'Union Station', type: 'development_co', district: 'downtown',
    blurb: 'Forty thousand people a day, every one of them carrying something, none of them looking at anybody.',
    op: 'left_luggage',
    // The building is about things being put down and picked up by somebody else. So is the key.
    item: 'locker_key',
  },
  {
    id: 'observatory', name: 'The Old Observatory', type: 'merchant_bank', district: 'heights',
    blurb: 'Nobody has looked at a star from up here in sixty years. The vault under it was never emptied.',
    op: 'dome_job',
    // Sixty years of nobody coming up here, and one man still turning the key every morning.
    person: {
      name: 'Bartholomew Teague', role: 'patron', trait: 'honest', nerve: 61,
      note: 'Caretaker at the Old Observatory. Still has every key to it, including the ones below.',
      skills: { tech: 8, brains: 6 },
    },
  },
];

export const LANDMARK_BY_OP = Object.fromEntries(LANDMARKS.map(l => [l.op, l])) as Record<string, LandmarkDef>;
export const LANDMARK_OPS = LANDMARKS.map(l => l.op);

/** The landmark selling this item, if any building does. Read by `sim/items.ts`. */
export const LANDMARK_BY_ITEM = Object.fromEntries(
  LANDMARKS.filter(l => l.item).map(l => [l.item!, l]),
) as Record<string, LandmarkDef>;
